### ISSUE TITLE
prior art

### ISSUE THREAD

**Issue by 1268** [jaytaph/gosub-browser#4]
I fully support you making a new browser, but are you really not reusing anything? surely you could use an existing HTML parser, and build your own browser on top of that? can you explain your rationale here?

**Comment by jaytaph** [comment]
I know there are a lot of components out there that allows me to basically "point-and-click" a browser. But one of the goals is to know more about the whole process. It's not until I actually wrote a tokenizer for the html5 stream, that made me aware of the complexity. This is much more work, and will definitely result in inferior code that has been written by many people much smarter than me.. but it gives - at least me - a good idea on how things work.   I know this is not for everybody, but I do think it's important that people still try and grasp the foundations of tech / internet. We seem to forget this knowledge because we can be dumb and use smart things, instead of be smart and use dumb things.

hope this helps!
